// GENERATED by job-search-os/shared/cv/sync_papers.py from shared/papers.yaml.
// Do not edit by hand - run shared/cv/sync_all.ps1.

export type Paper = {
  id: string;
  title: string;
  authors: string;
  note?: string;
  url?: string;
  slidesUrl?: string;
  abstract?: string;
  updated?: string;
  wip?: boolean;
};

export const papersById: Record<string, Paper> = {
  jmp: {
    id: "jmp",
    title: "Trade Restrictiveness Indices with Discriminatory Tariffs",
    authors: "with James Lake",
    note: "Presented at the Midwest Economic Theory and International Trade Meetings, Virginia Tech, 2025.",
    abstract: "Trade-restrictiveness indices summarize a country's tariff schedule as a single welfare-equivalent uniform tariff, but the existing indices assume most-favored-nation tariffs. Since 2018 the largest tariff changes—the US–China tariff war, retaliatory tariffs, and proliferating preferential agreements—have been discriminatory by design. We extend the trade-restrictiveness index to partner-specific tariffs while preserving its welfare interpretation and derive a closed-form decomposition into a \"level\" component (how much a country restricts trade) and a \"discrimination\" component (how unevenly it does so). Computing the indices from WITS/Comtrade data for 2017–2024, we find that the MFN-only index systematically understates trade distortions when discrimination is high, and the decomposition separates, for the first time in this framework, the welfare cost of discrimination from the cost of protection.",
  },
  shapley: {
    id: "shapley",
    title: "Cooperative Multilateral Tariff Negotiations: A Quantitative Analysis Using Shapley Value",
    authors: "with Georg Schaur",
    note: "Draft v2, August 2026.",
    url: "/files/papers/shapley.pdf",
    slidesUrl: "/files/papers/shapley-slides.pdf",
    updated: "2026-08-21",
    wip: true,
  },
  endorse: {
    id: "endorse",
    title: "The Impact of Mayoral Endorsements on Presidential Election Outcomes",
    authors: "with Matt Van Essen and Luiz Lima",
    note: "2024 J. Fred and Wilma Holly Award (best second-year paper).",
    url: "/files/papers/endorse.pdf",
    abstract: "We develop and estimate a structural model of mayoral endorsements in presidential elections as an anonymous Bayesian game with mean-field equilibrium. The mean-field formulation reduces equilibrium computation to a fixed point on the candidate simplex, independent of the number of mayors, making structural estimation tractable at the scale of an entire country. Identification follows a BLP-style logit inversion of observed log-odds onto type covariates and aggregate shares. We apply the framework to Brazil's coalition-mediated endorsement system (2014, 5,623 mayors) and France's individual parrainage system (2017 and 2022).",
    updated: "2026-04-26",
  },
  safwelfare: {
    id: "safwelfare",
    title: "Price Risk, Irreversible Investment, and the Welfare Benchmark for the Section 45Z Clean Fuel Production Credit",
    authors: "with T. Edward Yu",
    url: "/files/papers/safwelfare.pdf",
    slidesUrl: "/files/papers/safwelfare-slides.pdf",
    updated: "2026-08-26",
  },
  safrisk: {
    id: "safrisk",
    title: "How Should 45Z Pay for Risk? A Welfare-CVaR and Project-Finance Decomposition of the IRA Clean Fuel Production Credit",
    authors: "with T. Edward Yu",
    url: "/files/papers/safrisk.pdf",
    slidesUrl: "/files/papers/safrisk-slides.pdf",
    updated: "2026-08-26",
  },
  pork: {
    id: "pork",
    title: "Estimating Pork Primal Price Relationships Using a Threshold Vector Autoregressive Analysis",
    authors: "with Charles Martinez, Christopher N. Boyer, T. Edward Yu, and David Anderson",
    note: "SSRN working paper 4121953 (2022).",
    url: "https://papers.ssrn.com/abstract=4121953",
  },
};

export const orderedPapers = (order: string[]) => order.map((id) => papersById[id]);
