// GENERATED by job-search-os/shared/cv/sync_papers.py from shared/papers.yaml.
// Do not edit by hand - run shared/cv/sync_all.ps1.

export type Paper = {
  id: string;
  title: string;
  authors: string;
  note?: string;
  url?: string;
  slidesUrl?: string;
  abstract?: string;
  updated?: string;
  wip?: boolean;
};

export const papersById: Record<string, Paper> = {
  jmp: {
    id: "jmp",
    title: "Measured Quality Falls Within the Firm: Market Access and Chinese Exports",
    authors: "with James Lake",
    url: "/files/papers/jmp.pdf",
    abstract: "Better access to a market is expected to make exporters upgrade. We show it does the opposite, and we locate where. Using the removal of tariff uncertainty for Chinese exporters to the United States in 2002, and comparing a firm's shipments of a product to the United States against its shipments of the same product elsewhere, we find that measured export quality falls by about 14 percent for heavily exposed products against barely exposed ones, and that 78% of that decline survives inside firm-product-arm cells that ship in both periods. The fall is not markup compression: the quantity response falls short of what the price cut implies by exactly the amount the measurement identity requires. We then show that this class of evidence cannot go further. Measured quality is a linear combination of the price and quantity it is inferred from, so a degraded product and a widened clientele imply the same three coefficients. We set out what would separate them.",
    updated: "2026-09-23",
  },
  tri: {
    id: "tri",
    title: "Trade Restrictiveness Indices with Discriminatory Tariffs",
    authors: "with James Lake",
    note: "Presented at the Midwest Economic Theory and International Trade Meetings, Virginia Tech, 2025.",
    url: "/files/papers/tri.pdf",
    updated: "2026-10-01",
  },
  shapley: {
    id: "shapley",
    title: "A Weight-Free Benchmark for Multilateral Tariff Bargaining",
    authors: "with Georg Schaur",
    note: "Draft, August 2026.",
    url: "/files/papers/shapley.pdf",
    slidesUrl: "/files/papers/shapley-slides.pdf",
    updated: "2026-09-02",
    wip: true,
  },
  endorse: {
    id: "endorse",
    title: "A Mean-Field Game of Mayoral Endorsements: Identification and Evidence from Brazilian Coalitional Presidentialism",
    authors: "with Matt Van Essen and Luiz Lima",
    note: "2024 J. Fred and Wilma Holly Award (best second-year paper).",
    url: "/files/papers/endorse.pdf",
    slidesUrl: "/files/papers/endorse-slides.pdf",
    abstract: "A mayor's return from endorsing a presidential candidate falls as other mayors endorse the same one, so endorsement is a strategic discrete-choice game that has gone structurally unestimated: among Brazil's 5,570 mayors the joint action space is too large to enumerate. Anonymity collapses the problem. When payoffs depend on rivals only through aggregate shares, equilibrium is a fixed point on the candidate simplex whose dimension does not grow with the number of players, and the model estimates by least squares in milliseconds. Estimating it on Brazil's 2014 election, we then show what the exercise does not buy: the prize parameter is algebraically the average log-odds of alignment rescaled by the share of mayors classified as aligned, so it changes sign with the classification rule. What survives is reduced form. A close-race difference-in-differences design puts discretionary transfers to co-partisan mayors 10.6 percent above those of other coalition members and finds no premium on the formula-based transfer that leaves no discretion to allocate.",
    updated: "2026-08-26",
  },
  safwelfare: {
    id: "safwelfare",
    title: "Price Risk, Irreversible Investment, and the Welfare Benchmark for the Section 45Z Clean Fuel Production Credit",
    authors: "with T. Edward Yu",
    url: "/files/papers/safwelfare.pdf",
    slidesUrl: "/files/papers/safwelfare-slides.pdf",
    updated: "2026-09-26",
  },
  safrisk: {
    id: "safrisk",
    title: "How Should 45Z Pay for Risk? A Welfare-CVaR and Project-Finance Decomposition of the IRA Clean Fuel Production Credit",
    authors: "with T. Edward Yu",
    url: "/files/papers/safrisk.pdf",
    slidesUrl: "/files/papers/safrisk-slides.pdf",
    updated: "2026-09-26",
  },
  pork: {
    id: "pork",
    title: "Estimating Pork Primal Price Relationships Using a Threshold Vector Autoregressive Analysis",
    authors: "with Charles Martinez, Christopher N. Boyer, T. Edward Yu, and David Anderson",
    note: "SSRN working paper 4121953 (2022).",
    url: "https://papers.ssrn.com/abstract=4121953",
  },
};

export const orderedPapers = (order: string[]) => order.map((id) => papersById[id]);
